name: Run all tests inside repo/tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macOS]
        arch: [ARM64]

    runs-on:
      - self-hosted
      - ${{ matrix.os }}
      - ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        ./build_for_testing.sh
      working-directory: build
    - name: build_integration_tests
      run: |
        ./build_tests.sh
      working-directory: tests/integration_tests/build
    - name: run_integration_tests
      run: |
        sudo ./run_tests
      working-directory: tests/integration_tests/output
